"""Compatibility imports for SRD-derived reference data."""

from dming.srd_data import (
    ABILITY_MODIFIERS,
    CARRYING_CAPACITIES,
    CREATURE_SIZES,
    DIFFICULTY_CLASSES,
    LEVEL_ADVANCEMENT,
    PROFICIENCY_BONUSES,
)

__all__ = [
    "ABILITY_MODIFIERS",
    "CARRYING_CAPACITIES",
    "CREATURE_SIZES",
    "DIFFICULTY_CLASSES",
    "LEVEL_ADVANCEMENT",
    "PROFICIENCY_BONUSES",
]
